version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: manage_group_bot_1
    environment:
      POSTGRES_DB: manage_group_bot_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "15432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always
    networks:
      - postgres-network

networks:
  postgres-network:
    external: true

volumes:
  postgres-data: