version: '3.8'
services:
  postgres:
    image: postgres:16
    container_name: manage_group_bot_1
    environment:
      POSTGRES_DB: manage_group_bot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: always

  app:
    build: .
    container_name: manage_group_bot_1
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/manage_group_bot
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 123
    depends_on:
      - postgres
    ports:
      - "343:343"
    restart: always
    volumes:
      - /.../files:/app/files

volumes:
  postgres-data: