server:
  port: 343
spring:
  datasource:
    username: postgres
    password: 123
    url: jdbc:postgresql://localhost:5432/manage_group_bot
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
