package uz.pdp.appmanagegroupbot.enums;

public enum LangFields {
    SEND_YOUR_PHONE_NUMBER_TEXT,
    START_TEXT,
    BUTTON_REQUEST_CONTACT_TEXT,
    ABOUT_BOT_BUTTON,
    MONTHLY_TARIFF_TEXT,
    ADMIN_MENU_TEXT,
    ABOUT_BOT_TEXT,
    BACK_BUTTON,
    USE_BUTTONS_TEXT,
    ADMINS_CARD_INFO,
    PHOTO_SAVED_TEXT,
    WELCOME_TO_ADMIN_MENU_TEXT, NOT_PAID_TEXT,
    CHANGED_ADMIN_STATUS,
    SUBSCRIBED_USERS_LIST_TEXT,
    SCREENSHOTS_LIST_TEXT,
    ADMIN_ACCESS_DENIED, ADMIN_LEVEL_TEXT, ACCEPT_SCREENSHOT_TEXT, REJECT_SCREENSHOT_TEXT, EMPTY_SCREENSHOTS_LIST_TEXT, UN_CHECKED_SCREENSHOT_TEXT, AMOUNT_TEXT, SCREENSHOT_IS_VALID_TEXT, ACCEPTED_SCREENSHOT_TEXT, SCREENSHOT_IS_INVALID_TEXT, REJECTED_SCREENSHOT_TEXT, ACCEPTED_AT, REJECTED_AT, DOWNLOAD_AT, EMPTY_USERS_LIST_TEXT, HEADER_USERS_LIST_TEXT, ADMINS_LIST_TEXT


}

