package uz.pdp.appmanagegroupbot.enums;

public enum State {
    SENDING_CONTACT_NUMBER,
    SENDING_PHOTO,
    ADMIN_MENU,
    CHOOSE_USERS,
    SENDING_UPDATE_TO_ALL,
    SENDING_UPDATE_TO_SUBSCRIBED,
    SENDING_UPDATE_TO_NON_SUBSCRIBED,
    SELECTING_COURSES, SELECTING_FILIAL, ABOUT_CHANNEL, SENDING_UPDATE, START
}
